#!/bin/sh

# 定义一个包含特定分支名称的数组
specialBranches=("papaas-3.2.20-lts" "release/papaas-4.0.8" "release/papaas-4.1.1-rc")

# 获取当前仓库的分支
branchName=$(git symbolic-ref --short -q HEAD)

# 打印当前分支的名称
echo "当前分支：$branchName"

# 检查当前分支是否在特定分支数组中
if printf '%s\n' "${specialBranches[@]}" | grep -qx "$branchName"; then
  # 询问是否继续
  read -p "您正在推送到 $branchName 分支，是否继续? (yes/no): " confirm

  # 根据用户输入决定是否继续
  if [ "$confirm" != "yes" ]; then
    echo "推送已取消"
    exit 0
  fi
else
  # 询问是否继续
  read -p "是否继续执行, 按enter键将推送分支到远程..."
fi

# 推送分支到远程仓库
if ! git push origin $branchName; then
  echo "\033[31m推送失败，请检查错误信息\033[0m"
  exit 1
fi