#!/bin/sh

# 获取当前路径
current_path="$PWD"

# 定义不同 Node.js 版本需要的文件夹数组
node_16_folders=('apaas-playwright')
node_14_folders=('define' 'company-project')
node_18_folders=('github-project' 'another-folder-using-node-18')

contains_folder() {
  local folder_array=("$@")
  for folder in "${folder_array[@]}"; do
    if echo "$current_path" | grep -q "$folder"; then
      return 0
    fi
  done
  return 1
}

# 匹配 Node.js 版本的文件夹，并切换版本
if contains_folder "${node_16_folders[@]}"; then
  fnm use 16
elif contains_folder "${node_14_folders[@]}"; then
  fnm use 14
elif contains_folder "${node_18_folders[@]}"; then
  fnm use 18
else
  # 默认使用 Node.js 18
  fnm use 18
fi
